---
abstract: 'A Validation Framework for Web and Unix Centric Applications'
author:
  - 'Varun Juyal <varunjuyal123@yahoo.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Validation-Automation
provides:
  App::Validation::Automation:
    file: lib/App/Validation/Automation.pm
    version: 0.01
  App::Validation::Automation::Alarming:
    file: lib/App/Validation/Automation/Alarming.pm
    version: 0
  App::Validation::Automation::Logging:
    file: lib/App/Validation/Automation/Logging.pm
    version: 0
  App::Validation::Automation::Purging:
    file: lib/App/Validation/Automation/Purging.pm
    version: 0
  App::Validation::Automation::Unix:
    file: lib/App/Validation/Automation/Unix.pm
    version: 0
  App::Validation::Automation::Web:
    file: lib/App/Validation/Automation/Web.pm
    version: 0
requires:
  Carp: 0
  Config::Simple: 4.58
  Crypt::Lite: 0.082011
  Data::Dumper: 2.121_08
  English: 0
  Error::TryCatch: 0.07
  File::Basename: 0
  File::Path: 0
  Getopt::Long: 0
  HTML::Form::ForceValue: 0.007
  Mail::Sendmail: 0.79
  Moose: 2.0205
  Net::SSH::Perl: 1.34
  Switch: 0
  WWW::Mechanize: 1.70
  namespace::autoclean: 0.13
  perl: v5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
